#!/usr/bin/env python3
"""
ADO DevOps skill setup: check and persist credentials.

Usage:
  python setup.py status
      Show current configuration status (env vars + config file).

  python setup.py save [--org ORG] [--project PROJECT] [--pat PAT]
      Save one or more credentials to ~/.ado-devops.env

  python setup.py clear
      Remove the saved config file.

Credentials priority (highest to lowest):
  1. Environment variables (ADO_ORG, ADO_PROJECT, ADO_PAT)
  2. Config file: ~/.ado-devops.env
"""

import argparse
import json
import os
import stat
import sys

CONFIG_FILE = os.path.expanduser("~/.ado-devops.env")
DEFAULT_ORG = "tsmcit"
DEFAULT_PROJECT = "AI Operation Center"


def load_file_config():
    config = {}
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    config[k.strip()] = v.strip()
    return config


def cmd_status(args):
    file_config = load_file_config()

    def get_val(key):
        env_val = os.environ.get(key, "")
        file_val = file_config.get(key, "")
        if env_val:
            return env_val, "env"
        elif file_val:
            return file_val, "file"
        return "", "missing"

    org, org_src = get_val("ADO_ORG")
    project, project_src = get_val("ADO_PROJECT")
    pat, pat_src = get_val("ADO_PAT")

    # Proxy: check HTTP_PROXY and HTTPS_PROXY (env takes priority over file)
    http_proxy, http_proxy_src = get_val("HTTP_PROXY")
    https_proxy, https_proxy_src = get_val("HTTPS_PROXY")
    effective_proxy = http_proxy or https_proxy
    effective_proxy_src = http_proxy_src if http_proxy else https_proxy_src

    print(json.dumps({
        "config_file": CONFIG_FILE,
        "config_file_exists": os.path.exists(CONFIG_FILE),
        "defaults": {
            "ADO_ORG": DEFAULT_ORG,
            "ADO_PROJECT": DEFAULT_PROJECT,
        },
        "values": {
            "ADO_ORG":     {"value": org,              "source": org_src},
            "ADO_PROJECT": {"value": project,          "source": project_src},
            "ADO_PAT":     {"value": "***" if pat else "", "source": pat_src, "is_set": bool(pat)},
        },
        "proxy": {
            "HTTP_PROXY":  {"value": http_proxy,  "source": http_proxy_src},
            "HTTPS_PROXY": {"value": https_proxy, "source": https_proxy_src},
            "effective":   effective_proxy or None,
            "source":      effective_proxy_src if effective_proxy else "missing",
        },
        "ready": bool(org and project and pat),
    }, ensure_ascii=False, indent=2))


def cmd_save(args):
    file_config = load_file_config()

    if args.org:
        file_config["ADO_ORG"] = args.org
    if args.project:
        file_config["ADO_PROJECT"] = args.project
    if args.pat:
        file_config["ADO_PAT"] = args.pat
    if args.proxy:
        file_config["HTTP_PROXY"] = args.proxy
        file_config["HTTPS_PROXY"] = args.proxy
    if args.clear_proxy:
        file_config.pop("HTTP_PROXY", None)
        file_config.pop("HTTPS_PROXY", None)

    with open(CONFIG_FILE, "w") as f:
        f.write("# Azure DevOps credentials — auto-generated by ado-devops skill\n")
        for k, v in file_config.items():
            f.write(f"{k}={v}\n")

    # Restrict to owner read/write only (like SSH keys)
    try:
        os.chmod(CONFIG_FILE, stat.S_IRUSR | stat.S_IWUSR)
    except Exception:
        pass

    print(json.dumps({
        "saved": True,
        "config_file": CONFIG_FILE,
        "keys_saved": list(file_config.keys()),
    }, ensure_ascii=False, indent=2))


def cmd_clear(args):
    if os.path.exists(CONFIG_FILE):
        os.remove(CONFIG_FILE)
        print(json.dumps({"cleared": True, "config_file": CONFIG_FILE}))
    else:
        print(json.dumps({"cleared": False, "reason": "config file did not exist"}))


def main():
    parser = argparse.ArgumentParser(description="ADO DevOps skill setup")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("status", help="Show current configuration status")

    p_save = sub.add_parser("save", help="Save credentials to config file")
    p_save.add_argument("--org",          help="ADO organization name")
    p_save.add_argument("--project",      help="ADO project name")
    p_save.add_argument("--pat",          help="Personal Access Token")
    p_save.add_argument("--proxy",        help="Proxy URL (sets both HTTP_PROXY and HTTPS_PROXY), e.g. http://proxy.corp:8080")
    p_save.add_argument("--clear-proxy",  action="store_true", help="Remove proxy settings from config file")

    sub.add_parser("clear", help="Remove saved credentials")

    args = parser.parse_args()

    if args.command == "status":
        cmd_status(args)
    elif args.command == "save":
        cmd_save(args)
    elif args.command == "clear":
        cmd_clear(args)


if __name__ == "__main__":
    main()
